label good_end:
    f "I knew you had it in you. You should be proud of yourself..." 
    f "Not because you answered every question correctly."
    f "But because you reclaimed the memories that were once deeply buried, the ones you tried to forget"
    f "You are no longer a prisoner of your past."
    z "Mister.."
    f "Well, not trying to get too sentimental here, so let me be the one to announce this: You and your friend are free to go!"
    f "If you reopen the same door, you will slowly feel yourself waking up."
    z "Huh, so it's finally over."
    n "Yeah, this whole experience was super draining.."
    f "You'd be right there, all these missions were created to freshen up Zuha's memory, but i had slight feeling that she needed the help of a friend to help her along her journey."
    f "This is exactly why this shared space was created for the two of you in the first place."
    "Oh i see, so this whole time. She was meant to be here alongside me to guide me."
    z "I'm ready to leave, and you?"
    n "Ive been long ready.. trust me!"
    "I'm relieved this is all finally over, but i've got a feeling that i'll miss this place, soon enough."
    "i stretched out my hand as i pulled the door handle."
    "I can see the exact white void i saw earlier, but somehow, my minds getting kind of dizzy.."
    z "Noor, are you feeling it aswell?"
    n "W-what? oh, yeah i do, but it's okay, see."
    n " We've almost reached the end of the... "
    #show cg art of zuha shockingly waking up in her bed
    z "Wh-What? i'm finally, we're finally ho-!"
    n "..Zz.."
    z "home.. Wow, for how long did we sleep, it's now almost-"
    z "SUNRISE?? HERE AT SCHOOL???"
    z "NOOR, WAKE UP, WAKE UP!!?!??!"
    n "Hah—! ughh.. could you have woken me up a little more.."
    n "Ah. It's sunrise"
    z "YEAH, i missed my parents calls like 80 times.. im so done for."
    n "Heh.. same for me, well we should probably just stay here, first period is almost gonna start anyway"
    z "Ugh, your right, we'll probably be late by the time we'll go back to school."
    n "I'll head out to the cafeteria for now, want something?"
    z "No thanks, I'll see you later!"
    n "Bye, and don't doze off again"
    z "Heh, isn't that rich coming from you..."
    "..."
    "So we really left, we cleared every mission and i got my memories back."
    "I don't know how things will go on from here, but i know one thing for sure."
    "It's that i've now got someone who i can call a true friend."
